ports:
- port: 3000
tasks:
- init: >
   sudo apt-get install openjdk-11-jdk &&
   cd xtext-railmap-language-server &&
   ./gradlew shadowJar &&
   cd .. &&
   yarn
  command: >
   cd app &&
   yarn start ../workspace
vscode:
  extensions:
    - grammarcraft.xtext-lang@0.4.0:w2H9TVrWxFKd03NAD9MBJA==
    - GrammarCraft.xtend-lang@0.1.0:Imxa0vYqAEpd11eN0u1gqw==
